---
title: "lol_markdown"
output: html_document
date: "2022-11-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### Basic rundown of League of Legends E-Sports

League of Legends is a MOBA (Multiplayer Online Battle Arena), a 5 v 5 action game that has players picking certain characters known as champions. Each player takes on one of 5 different roles: Top Lane, Jungle, Mid Lane, Attack Damage Carry, and Support. There are over 162 champions in League of Legends and each champion is made for one of these 5 roles, some champions can be played in many different roles but most are tailored to one role. Without going into detail about the whole game and how it works, the main purpose of this project is to see if having a diverse champion pool makes a good team. Is the ability to use multiple different champions something professional teams strive for? 

The Worlds 2022 dataset is provided by [oracleselixir.com](http://oracleselixir.com). They have a nice packaged csv file that has all of 2022 league of legends e-sports. Worlds is the biggest and most recent tournament in league of legends e-sports. According to escharts.com, Worlds 2022 had a peak of 5.1 million concurrent viewers across different streaming platforms and languages.


### Technical Goals

This exploratory data analysis is done with R to improve skills in:

1. Data wrangling with dplyr
2. Data visualization with ggplot2 
3. Creating interactive web apps with shinyapp

### Main Questions

The purpose of this project is to see what are the benefits to having a diverse champion pool.

1. What champions at Worlds 2022 where used in multiple different roles?
2. What roles have the most champion diversity at Worlds 2022? 
3. Which teams had the most champion diversity at Worlds 2022? 
4. Which players had the most champion diversity at Worlds 2022? 

### Player Unique Champions webapp
[Web App](https://yunghiro.shinyapps.io/lol_2022/)

Throughout my time working on the dataset one of the things that I was always looking at was how many unique champs did x player have. There were over x amount of players at worlds across x amount of teams. I initially made a chart but it was tiresome to scour the chart for specific players and there data. My solution was to create an interactive webapp that shows you all the champions each player has picked and how many times they picked each champion throughout there tournament run. 


### Roles with the most champion diversity
### Players with the most unique champions played 

### Overall thoughts on Champion Diversity, Is it good or bad?

The main factors that affected champion diversity was role and number of games. What role you played had more of an effect on champion diversity compared to the number of games played. Looking at the scatterplot for unique champs over games played for teams, it clearly shows that more games played = more champion diversity but when looking at player data there was less of a correlation. Team data isn't indicitive that there is a high correlation because team data takes into account all 5 roles and naturally will increase the champion diversity compared to player data. Number of games does have a natural affect on champion diversity. DRX was the team that won worlds 2022 and played the most games at 26. All 5 of 

My initial hypothesis for which roles had the highest champion diversity would be top-lane, mid-lane, and support. Historically in League of Legends, these roles have more characters that are played in between these roles. Majority of champions that were played in multiple roles were played between 

Jungle and Attack Damage Carry are both very hyperfocused roles. Looking at the data for worlds 2022, it showed that Jungle and Attack Damage Carry had the lowest champion diversity per role but mid-lane was closer to those two roles than the other. 

This goes into the other factor that affects champi

